CREATE TABLE books (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title VARCHAR(500) NOT NULL,
  author VARCHAR(500) NOT NULL DEFAULT '',
  normalized_title VARCHAR(500) NOT NULL,
  normalized_author VARCHAR(500) NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT uk_books_normalized_title_author UNIQUE (normalized_title, normalized_author)
);

CREATE TABLE notes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  book_id BIGINT NOT NULL,
  content TEXT NOT NULL,
  chapter_name VARCHAR(500),
  remark TEXT,
  favorite BOOLEAN NOT NULL DEFAULT FALSE,
  source_hash VARCHAR(64),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_notes_book FOREIGN KEY (book_id) REFERENCES books (id) ON DELETE CASCADE,
  CONSTRAINT uk_notes_source_hash UNIQUE (source_hash)
);

CREATE TABLE reading_events (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  note_id BIGINT,
  viewed_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
  duration_seconds INTEGER NOT NULL DEFAULT 0,
  CONSTRAINT fk_reading_events_note FOREIGN KEY (note_id) REFERENCES notes (id) ON DELETE SET NULL,
  CONSTRAINT ck_reading_events_duration_nonnegative CHECK (duration_seconds >= 0)
);

CREATE INDEX idx_notes_book_id ON notes (book_id);
CREATE INDEX idx_notes_favorite ON notes (favorite);
CREATE INDEX idx_reading_events_note_id ON reading_events (note_id);
CREATE INDEX idx_reading_events_viewed_at ON reading_events (viewed_at DESC);
